# Site settings
title: GA Interview Presentations
email: lynch.r.j@gmail.com
description: "A series of presentations for an interview at GA"
baseurl: "/ga_interview_presentations"
url: "http://shiftyp.github.io/ga_interview_presentations"

# Build settings
markdown: kramdown
permalink: pretty
