# Site settings
title: Interview Presentations
email: lynch.r.j@gmail.com
description: "A series of presentations for an interview at GA"
baseurl: "/interview_presentations"
url: "http://shiftyp.github.io/interview_presentations"

# Build settings
markdown: kramdown
permalink: pretty
